# WAS 서비스 포트 설정
server:
  port: 8888

  servlet:
    contextPath: /devpro
  
# Actucator 활성화
#management:
#  security:
#    enabled: false

# Spring 환경 설정
spring:

#  # 1개 DataSource 설정
#  datasource:
#    h2:
#      platform: h2
#      driverClassName: org.h2.Driver
#      jdbcUrl: jdbc:h2:~/test;AUTO_SERVER=TRUE
#      username: sa
#      password: sa

  # 2개 이상 DataSource 설정(config 경로에서 DataSource 설정 필요)
  datasource:
    hikari:
      h2:
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:synodb
        username: sa
        password:
      hsql:
        driver-class-name: org.hsqldb.jdbc.JDBCDriver
        jdbc-url: jdbc:hsqldb:file:~/hsqltest;encoding=UTF-8
        username: sa
        password:
      mysql:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/note?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: root
      maria:
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:3307/testdb?useUnicode=true&charaterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: scott
        password: tiger

#  # 분산 트랜잭션(2PC) DataSource 설정(config 경로에서 DataSource 설정 필요)
#  jta:
#    enabled: true
#    service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
#    max-actives: 200
#    enable-logging: falseps -ef
#
#    atomikos:
#      datasource:
#        primary:
#          unique-resource-name: dataSource
#          max-pool-size: 5
#          min-pool-size: 1
#          max-life-time: 20000
#          borrow-connection-timeout: 10000
#          xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
#          xa-properties:
#            user: sa
#            password:
#            URL: jdbc:h2:~/test;DB_CLOSE_DELAY=-1
#
#        second:
#          unique-resource-name: secondDataSource
#          max-pool-size: 5
#          min-pool-size: 1
#          max-life-time: 20000
#          borrow-connection-timeout: 10000
#          xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
#          xa-properties:
#            user: sa
#            password:
#            URL: jdbc:h2:~/test2;DB_CLOSE_DELAY=-1



# Log4j2 기본 설정
logging:
  config: classpath:log4j2.xml
  level:
    ROOT: DEBUG

# 웹 관련 설정
web:
  config:
    # 페이지 당 기본 게시물 갯수
    default-page-size: 10